# Generated by Django 5.0.1 on 2024-04-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0004_remove_team_project_remove_team_seeks_user_contacts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamad',
            old_name='requirements',
            new_name='role',
        ),
        migrations.AddField(
            model_name='teamad',
            name='skills',
            field=models.CharField(default='', max_length=2047),
        ),
    ]
