# Generated by Django 5.0.1 on 2024-04-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0005_rename_requirements_teamad_role_teamad_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reqinv',
            name='invite',
        ),
    ]
