# Generated by Django 5.0.1 on 2024-04-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0006_remove_reqinv_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqinv',
            name='invite',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
