# Generated by Django 5.0.1 on 2024-04-19 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_team_teammembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembership',
            name='ownership',
        ),
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='start.team'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
